### PR TITLE
Allow enum variant as hashmap key

### PR DESCRIPTION
**Pull request by oli-obk**
merge after #31 
closes https://github.com/rust-lang/rust/issues/21470 here

### CODE REVIEW

**Comment by huonw** [comment]
Does this work with `Decodable`?

**Comment by oli-obk** [comment]
huonw: that's how it worked before, but i'll add a test

**Comment by oli-obk** [comment]
@huonw i changed the test to also check if deserialize still works.
actually i think rust will decode almost everything, even invalid json like `{0:"hi"}` without complaint. It just won't create invalid json

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
