### PR TITLE
use new IO crate

### PR DESCRIPTION
**Pull request by zonyitoo**
Make JSON module compatible with the new IO crate.

### CODE REVIEW

**Comment by BurntSushi** [comment]
This is great, and it's nice to see that it didn't require that many changes!

I will beg the powers that be not to merge this yet though. I don't think the world is ready for `std::io` yet (there are still some [really important things missing that are scheduled for this week](https://github.com/rust-lang/rust/issues/22500)), and `rustc-serialize` is a core library that tons of crates depend on.

**Comment by zonyitoo** [comment]
I have spent a whole day on migrating my small project to be compatible with the new IO crate. ;)

**Comment by alexcrichton** [comment]
While `std::io` may not be fully fleshed out yet I would like to make progress in allowing dependencies to update to using `std::io` wherever possible. I'm going to publish this as a new series of releases on crates.io so you can still opt-in to the `std::old_io` behavior. We can also perhaps maintain a branch for a bit with `std::old_io` as well.

**Comment by alexcrichton** [comment]
I've created an [old-io](https://github.com/rust-lang/rustc-serialize/tree/old-io) branch we can use to maintain the `0.2.x` series temporarily.

**Pull request merged**
