### PR TITLE
Fallout from `os` stabilization

### PR DESCRIPTION
**Pull request by tamird**
See https://github.com/rust-lang/rust/commit/542e2bb

### CODE REVIEW

**Comment by alexcrichton** [comment]
I think this will have to wait until the changes land on nightly, but in the meantime can you change them to `use std::os::unix::prelude::*`? That way we should be able to land it right away!

**Comment by tamird** [comment]
done! thanks!

**Comment by tamird** [comment]
@alexcrichton would you mind releasing this as 0.3.4?

**Comment by alexcrichton** [comment]
Sure!

**Pull request merged**
